# Generated by Django 3.2.5 on 2024-11-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('suburl', models.CharField(blank=True, max_length=1000, null=True)),
                ('keyword', models.CharField(blank=True, max_length=800, null=True)),
                ('news_title', models.CharField(blank=True, max_length=800, null=True)),
                ('news_content', models.TextField(blank=True, null=True)),
                ('news_release_time', models.CharField(blank=True, max_length=100, null=True)),
                ('crawler_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crawler_data',
            },
        ),
    ]
