# Generated by Django 3.2.5 on 2024-11-07 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crawlerdata',
            table=None,
        ),
    ]
